# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4aef6c9e77c322fec6c01a38eb3ad7c29b2b0f607dffa7bbd31a537c3bb0e8bf22276d54acae25d0c66086715f73689fc0042df3c215f877c5c1b72c58e3eba0

test:
  secret_key_base: 5bd4be3090378d420197ee89937096e3c76102fa34df2c3d6957a3fac76ffe1f11da9e233ee22c0e6c1dd77d5d89692bfbcc26f38e01aa404e13254584b14997

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
